force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/PhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/StudentCreator.cls
@isTest
public with sharing class StudentCreator {
    public static void createStudent() {
        Student__C newStudent = new Student__C();

        Employee__c advisor = [SELECT Id FROM Employee__c LIMIT 1];
        newStudent.Advisor__c = advisor.Id;
        newStudent.Name = 'Greg Maddox';
        newStudent.Age__c = 25;
        newStudent.Email__c = 'gmaddox@gmail.com';
        newStudent.PhoneNumber__c = '0000000000';

        insert newStudent;
    }
}