force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateEnrollmentTriggerTest.cls
@isTest
public class DuplicateEnrollmentTriggerTest 
{
    @TestSetup
    static void makeData()
    {
        SchoolDataCreator.createData();
        Student__c s = [SELECT Id FROM Student__c LIMIT 1];
        Class__c c = [SELECT Id FROM Class__c LIMIT 1];
        ClassEnrollment__c ce = new ClassEnrollment__c();
        ce.Student__c = s.Id;
        ce.Class__c = c.Id;
        ce.Credits__c = 1;
        insert ce;
    }  

    @isTest
    public static void testSingleInsert()
    {
        Test.startTest();
        ClassEnrollment__c ce = [SELECT Id, Student__c, Class__c FROM ClassEnrollment__c LIMIT 1];
        ClassEnrollment__c ce1 = new CLassEnrollment__c();
        ce1.Student__c = ce.Student__c;
        ce1.Class__c = ce.Class__c;
        ce1.Credits__c = 7;
 
        try 
        {
            insert ce1;
        } catch (Exception e) 
        {
            System.assertEquals(1, [SELECT Id FROM ClassEnrollment__c].size());
            System.assert(e.getMessage().contains(duplicateEnrollmentTriggerHelper.DUPLICATE_ENROLLMENT));    
        }
            
        
        Test.stopTest();
    }


    @isTest
    public static void testMultipleInsert()
    {
        Test.startTest();
        ClassEnrollment__c ce = [SELECT Id, Student__c, Class__c FROM ClassEnrollment__c LIMIT 1];
        List<Student__c> s = [SELECT Id FROM Student__c LIMIT 3 OFFSET 2];
        List<Class__c> c = [SELECT Id FROM Class__c LIMIT 3 OFFSET 2];
        ClassEnrollment__c ce1 = new ClassEnrollment__c();
        CLassEnrollment__c ce2 = new ClassEnrollment__c();
        ClassEnrollment__c ce3 = new ClassEnrollment__c();
        List<CLassEnrollment__c> ceList = new List<ClassEnrollment__c>();

        // duplicate
        ce1.Student__c = ce.Student__c;
        ce1.Class__c = ce.Class__c;
        ce1.Credits__c = 7;
        ceList.add(ce1);

        ce2.Student__c = s[0].Id;
        ce2.Class__c = c[0].Id;
        ce2.Credits__c = 6;
        ceList.add(ce2);

        ce3.Student__c = s[1].Id;
        ce3.Class__c = c[1].Id;
        ce3.Credits__c = 9;
        ceList.add(ce3);

        List<Database.SaveResult> results = Database.insert(ceList, false);
        System.assertEquals(3, [SELECT Id FROM CLassEnrollment__c].size());
        System.assertEquals(results[0].getErrors()[0].getMessage(), duplicateEnrollmentTriggerHelper.DUPLICATE_ENROLLMENT);
        

        Test.stopTest();
    }
}