force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Degree__c/Degree__c.object-meta.xml
<CustomObject>
    <label>Degree</label>
    <nameField>
        <label>Degree Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degrees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DegreeAndClassEvaluation.cls
/**
 * Created by gamedevmadeeasy on 10/13/19.
 */

public with sharing class DegreeAndClassEvaluation {
    public ClassEnrollment__c checkStudentDegreeVsClass(Degree__c degree, Class__c classType) {
        // In order for a Student to be enrolled in a class, their degree must be related to the class.
        //    - i.e., the same department
        //    - If successfully enrolled, the CE status should be set to `Enrolled`
        //    - If it was not successful, the CE status should be set to `Denied`
        //    - If enrolled, email the teacher.
        //    - If denied, email the student that an UnrelatedDegreeException exception was thrown.
    }
}