force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateClassEnrollmentTests.cls
@isTest
public with sharing class DuplicateClassEnrollmentTests {
    @TestSetup
    static void makeData(){
        DepartmentCreator.createDepartment();
        EmployeeCreator.createEmployee();
        StudentCreator.createStudent();

        RoomCreator.createRoom();
        TopicCreator.createTopic();
        ClassCreator.createClass();
    }

    @isTest static void testPreventDuplicateClassEnrollment() {
        Student__c mockStudent = [SELECT Id FROM Student__c];
        Class__c mockClass = [SELECT Id FROM Class__c];
        ClassEnrollment__c mockClassEnrollment = new ClassEnrollment__c();
        mockClassEnrollment.Class__c = mockClass.Id;
        mockClassEnrollment.Student__c = mockStudent.Id;
        mockClassEnrollment.Credits__c = 50;

        insert(mockClassEnrollment);

        Test.startTest();
        Database.SaveResult insertResult = Database.insert(mockClassEnrollment, false);
        Test.stopTest();

        List<ClassEnrollment__c> testExistingClassEnrollments = [SELECT Id FROM ClassEnrollment__c WHERE Student__c =: mockStudent.Id AND Class__c =: mockClass.Id];

        System.assertEquals(1, testExistingClassEnrollments.size());
    }
}