force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectOnePartOne.cls
public with sharing class ProjectOnePartOne {
    
    public static Integer fibonacci(Integer n) {
        n--;
        List<Integer> sequence = new List<Integer>{1,1,2,3};
        
        if(n<4){
            return sequence[n];
        }
        else{
            for(Integer i = 4; i < (n + 1); i++) {
                sequence.add(sequence[i-1] + sequence[i-2]);
            }
            return sequence[n];
        }
    }

    public static String reverseString(String s) {
        String reversed = '';
        for(Integer i = s.length() -1; i > -1; i--){
            reversed += s.substring(i,(i+1));
        }
        return reversed;
    }

    public static Integer factorial(Integer n) {
        Integer f = 1;
        n++;
        for(Integer i = 1; i < n; i++) {
                f*= i;
        }
        return f;
    }

    public static Boolean isPalindrome(String s) {
        //boolean palindrome = true;
        String reversed = reverseString(s);
        for (Integer i = 0; i < s.length(); i++){
            if(!s.substring(i,(i+1)).equals(reversed.substring(i,(i+1)))){
                return false;
            }
        }
        return true;
    }
    
    public static List<Account> getAccountsForAGivenState(State s) {
        List<Account> stateAccounts = new List<Account>();
        List<Id> sameStateAccounts = new List<Id>();
        List<State> states = State.values();
        State compareState = null;
        List<Account> accounts = [SELECT Id , BillingAddress FROM Account];
        for (Account a: accounts) {
            for(State stateEnum : states){
               if(a.BillingAddress.getState() == stateEnum.name()){
                   compareState = stateEnum;
               } 
            }
            if(compareState == s){
                sameStateAccounts.add(a.Id);
            }
        }
        boolean alreadyAdded = false;
        List<Contact> contacts = new List<Contact>();
        for(Id i: sameStateAccounts){
            contacts = [SELECT Id , MailingAddress FROM Contact WHERE AccountID = :i];
            for (Contact c: contacts) {
                if(!alreadyAdded){
                    for(State stateEnum : states){
                        if(c.MailingAddress.getState() == stateEnum.name()){
                            compareState = stateEnum;
                        }     
                    }
                    if(compareState == s){
                        stateAccounts.addAll([SELECT Id , BillingAddress FROM Account WHERE Id = :i]);
                        alreadyAdded = true;
                    }
                }
            }
        }

        return stateAccounts;
    }
    public static Map<Id, Map<Id, Double>> getClassGrades() {
        Map<Id, Map<Id, Double>> studentsClassGrades = new Map<Id, Map<Id, Double>>();
        Map<Id, Double> tempClassGrades = new Map<Id, Double>();
        List<Double> grades = new List<Double>();
        Double gradeSum = 0.0;
        for(Student__c s: [SELECT Id FROM Student__c]){
            for(ClassEnrollment__c ce : [SELECT Id, Class__c FROM ClassEnrollment__c WHERE Student__c = :s.Id]){
                for(Class__C c : [SELECT Id FROM Class__c WHERE Id = :ce.Class__c]){
                    for(Grade__c g: [SELECT Grade__c FROM Grade__c WHERE Class_Enrollment__c =: ce.Id]){
                        gradeSum += g.Grade__c;
                    }       
                    if(grades.size() > 0){
                    tempClassGrades.put(c.Id, (gradeSum/grades.size()));
                    }
                }
            }
            if(grades.size() > 0){
                studentsClassGrades.put(s.Id,tempClassGrades.clone());
            }
            tempClassGrades.clear();
            gradeSum = 0.0;
        }
        return studentsClassGrades;
    }

}