force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestClass.cls
@isTest

public with sharing class TestClass {

    @isTest
    static void testFibonacci(){
        System.assertEquals(1, P1Test.fibonacci(1));
        System.assertEquals(2, P1Test.fibonacci(3));
        System.assertEquals(5, P1Test.fibonacci(5));


}

    @isTest
    static void testReverseString(){
        
        System.assertEquals('god', P1Test.reverseString('dog'));
        System.assertEquals('rats', P1Test.reverseString('star'));
        System.assertEquals('enohp', P1Test.reverseString('phone'));

    }

    @isTest
    static void testFactorial(){
        System.assertEquals(1, P1Test.factorial(0));
        System.assertEquals(120, P1Test.factorial(5));
        System.assertEquals(6, P1Test.factorial(3));

    }

    @isTest
    static void testIsPalindrome(){
        System.assertEquals(True, P1Test.isPalindrome('dod'));
        System.assertEquals(True, P1Test.isPalindrome('racecar'));
        System.assertEquals(True, P1Test.isPalindrome('mom'));
        
    }

    @isTest
    static void testGetAccountsForAGivenState(){

        Account mockAccountState = new Account();
        mockAccountState.Name = 'Him';
        mockAccountState.BillingState = 'CA';
        insert mockAccountState;

        Contact mockContactState = new Contact();
        mockContactState.lastName ='Toby';
        mockContactState.MailingState = 'CA';
        mockContactState.AccountId = mockAccountState.Id;
        insert mockContactState;

        mockAccountState = new Account();
        mockAccountState.Name = 'Her';
        mockAccountState.BillingSTate = 'PA';
        insert mockAccountState;

        mockAccountState = new Account();
        mockAccountState.Name = 'It';
        mockAccountState.BillingSTate = 'DE';
        insert mockAccountState;

        //size is 1
        System.assertEquals(1, P1Test.getAccountsForAGivenState(State.CA).size());
        
    }

    @isTest(SeeAllData = true) 
    static void  testgetClassGrades(){

        //SchoolDataCreator.createData();
        Student__c studentID = [SELECT id FROM Student__c LIMIT 1];
        Class__c classID = [SELECT id FROM Class__c LIMIT 1];
        //need mock data of student, grade, CE
        ClassEnrollment__c mockCE = new ClassEnrollment__c(
            Class__c = classID.Id,
            Student__c = studentID.Id,
            Credits__c = 4,
            Status__c = 'Enrolled'
        );
        insert mockCE;

        Map<Id, Map<Id, Double>> getSameGrade = P1Test.getClassGrades();
        
        for(Map<Id, Double> getGradeAndDouble : getSameGrade.values()){
            //returns size 2
            //System.assertEquals(0, getGradeAndDouble.size(), 'student: ');
            for(Double getExistingGrade : getGradeAndDouble.values()){
                //Grade is 70 or 80
                System.assertNotEquals(60,getExistingGrade);

            }
        }
    }



}