force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateEnrollmentTriggerHelper.cls
public with sharing class DuplicateEnrollmentTriggerHelper {
   
    public final static String DUPLICATE_ENROLLMENT = 'Student cannot be enrolled in the same class twice.';

    public static void preventDoubleEnrollment(List<ClassEnrollment__c> enrollmentsBeingInserted) {
        checkForDoubleEnrollment(enrollmentsBeingInserted);
    }

    public static void checkForDoubleEnrollment(List<ClassEnrollment__c> enrollmentsBeingInserted) {
        try {

            // Get the list of classes and list of students in Trigger.New 
            // (enrollmentsBeingInserted) and use those Ids to get a list of 
            // existing records with those same Ids. 
            // If any records exist already, then there is a duplicate enrollment
            List<Id> listOfClasses = new List<Id>();
            List<Id> listOfStudents = new List<Id>();

            for (ClassEnrollment__c classEnrollment : enrollmentsBeingInserted) {
                listOfClasses.add(classEnrollment.Class__c);
                listOfStudents.add(classEnrollment.Student__c);
            }

            List<ClassEnrollment__c> existingRecords = [
                SELECT 
                    Class__c 
                    ,Student__c 
                FROM ClassEnrollment__c 
                WHERE Class__c IN: listOfClasses
                    AND Student__c IN: listOfStudents
            ];

            if (existingRecords.size() > 0) {
                enrollmentsBeingInserted[0].addError(DUPLICATE_ENROLLMENT);
                //throw new DuplicateEnrollmentException(DUPLICATE_ENROLLMENT);
            }
        } catch (DuplicateEnrollmentException dee) {
            System.debug(dee.getMessage());
        }
    }
}