force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Degree__c/Degree__c.object-meta.xml
<CustomObject>
    <label>Degree</label>
    <nameField>
        <label>Degree Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degrees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Major__c/Major__c.object-meta.xml
<CustomObject>
    <label>Major</label>
    <nameField>
        <displayFormat>MAJOR-{0000}</displayFormat>
        <label>Major Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Majors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Major__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Degree</label>
    <referenceTo>Degree__c</referenceTo>
    <relationshipLabel>Majors</relationshipLabel>
    <relationshipName>Majors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Major__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Majors</relationshipLabel>
    <relationshipName>Majors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/CumulativeGPA__c.field-meta.xml
<CustomField>
    <fullName>CumulativeGPA__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Cumulative GPA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/MajorGPA__c.field-meta.xml
<CustomField>
    <fullName>MajorGPA__c</fullName>
    <label>Major GPA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GPAControllerTests.cls
@isTest
public with sharing class GPAControllerTests {

    @TestSetup
    static void makeData(){
        //inserts random Grade Data
        SchoolDataCreator.createData();
    }

    @isTest
    public static void calculateGPATester() {

        Test.startTest();

        Student__c aStudent = [SELECT Id FROM Student__c LIMIT 1 OFFSET 2];
        List<Grade__c> theirGrades = [SELECT Id,Grade__c FROM Grade__c WHERE Class_Enrollment__r.Student__c=:astudent.id];

        Id degree = [SELECT Degree__c FROM Major__c WHERE Student__c =:astudent.Id LIMIT 1].Degree__c;
        List<Grade__c> theirMGrades = 
            [SELECT Id,Grade__c FROM Grade__c WHERE Class_Enrollment__r.Student__c=:astudent.id AND Class_Enrollment__r.Class__r.Topic__r.Degree__c=:degree];

        //calculate gpa manually
        Double gradeAvg = 0;
        Double total = 0;
        for(Grade__c g:theirGrades )
        {
            total += Double.valueOf(g.Grade__c);
        }
        if(theirGrades.size()!=0)
            gradeAvg = total/theirGrades.size();

        Double mgradeAvg = 0;
        total = 0;
        for(Grade__c g:theirMGrades)
        {
            total += Double.valueOf(g.Grade__c);
        }
        if(theirMGrades.size()!=0)
            mgradeAvg = total/theirMGrades.size();

        
        Double expGPA = GPAController.getGPAFromAvg(gradeAvg);
        Double expmGPA = GPAController.getGPAFromAvg(mgradeAvg);


        //testing the method
        GPAController.calculateGPA(aStudent.Id);

        Student__c student = [SELECT Id,CumulativeGPA__c,MajorGPA__c FROM Student__c WHERE Id =:aStudent.Id LIMIT 1];

        //check
        System.assertEquals(student.CumulativeGPA__c,expGPA,'GPA does not match');
        System.assertEquals(student.MajorGPA__c,expmGPA,'GPA does not match');

        Test.stopTest();

    }
}