force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateClassEnrollmentTriggerHelper.cls
public with sharing class DuplicateClassEnrollmentTriggerHelper {
    public static void preventDuplicateClassEnrollment(ClassEnrollment__c classEnrollmentBeingInserted) {
        List<ClassEnrollment__c> existingClassEnrollments = [SELECT Id, Class__c, Student__c FROM ClassEnrollment__c];
        List<ClassEnrollment__c> denyClassEnrollment = new List<ClassEnrollment__c>();

        for (ClassEnrollment__c classEnrollment : existingClassEnrollments) {
            if (classEnrollment.Student__c == classEnrollmentBeingInserted.Student__c && classEnrollment.Class__c == classEnrollmentBeingInserted.Class__c) {
                denyClassEnrollment.add(classEnrollmentBeingInserted);
                break;
            }
        }

        denyDuplicateClassEnrollment(denyClassEnrollment);
    }

    public static void denyDuplicateClassEnrollment (List<ClassEnrollment__c> denyClassEnrollment) {
        for (ClassEnrollment__c classEnrollment : denyClassEnrollment) {
            classEnrollment.addError(UserPermissionErrors.ALREADY_ENROLLED_IN_THIS_CLASS);
            throw new DuplicateEnrollmentException();
        }
    }
}