force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/DaysPerWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysPerWeek__c</fullName>
    <label>Days per Week</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Degree__c/Degree__c.object-meta.xml
<CustomObject>
    <label>Degree</label>
    <nameField>
        <label>Degree Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degrees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Degree__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Degrees</relationshipLabel>
    <relationshipName>Degrees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>Rm-{0000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Degree</label>
    <referenceTo>Degree__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataCreator.cls
public with sharing class TestDataCreator {
    public static void createDataForEnrollment(){
		// Create Two Departments
		List<Department__c> departments = new List<Department__c>();
		Department__c d1 = new Department__c(Name = 'Math');
		Department__c d2 = new Department__c(Name = 'History');
		departments.add(d1);
		departments.add(d2);
		insert departments;
		System.debug('Departments Created');

		// Create Two Advisors
		List<Employee__c> advisors = new List<Employee__c>();
		Employee__c emp1 = new Employee__c(Name = 'Advisor 1', Department__c = d1.Id);
		Employee__c emp2 = new Employee__c(Name = 'Advisor 2', Department__c = d2.Id);
		advisors.add(emp1);
		advisors.add(emp2);
		insert advisors;
		System.debug('Advisors Created');

		// Create Student
		Student__c student = new Student__c(Name = 'TestStudent', Email__c = 'whocares@neglect.com', Advisor__c = emp1.Id, Status__c = 'Enrolled');
		insert student;
		System.debug('Student Created');

		// Create Degrees
		List<Degree__c> degrees = new List<Degree__c>();
		Degree__c deg1 = new Degree__c(Name = 'Mathematics', Department__c = d1.Id);
		Degree__c deg2 = new Degree__c(Name = 'History', Department__c = d2.Id);
		degrees.add(deg1);
		degrees.add(deg2);
		insert degrees;
		System.debug('Degrees Created');

		// Create Topics
		List<Topic__c> topics = new List<Topic__c>();
		Topic__c topic1 = new Topic__c(Name = 'Statistics', Degree__c = deg1.Id);
		Topic__c topic2 = new Topic__c(Name = 'American History', Degree__c = deg1.Id);
		topics.add(topic1);
		topics.add(topic2);
		insert topics;
		System.debug('Topics Created');

		// Create Classes
		List<Class__c> classes = new List<Class__c>();
		Class__c class1 = new Class__c(Name = 'TTT000', 
									   Capacity__c= 10, 
									   DaysPerWeek__c= 3, 
									   Department__c= d1.Id, 
									   StartDate__c=(Date.newInstance(2019, 8, 12)), 
									   EndDate__c=(Date.newInstance(2019, 12, 15)), 
									   Room__c = new Room__c().Id, 
									   ScheduledTime__c=(Time.newInstance(9, 0, 0, 0)), 
									   Status__c= 'In Progress', 
									   Topic__c= topic1.Id);

		Class__c class2 = new Class__c(Name = 'RRR000', 
									   Capacity__c= 10, 
									   DaysPerWeek__c= 5, 
									   Department__c= d2.Id, 
									   StartDate__c=(Date.newInstance(2019, 7, 12)), 
									   EndDate__c=(Date.newInstance(2019, 11, 13)), 
									   Room__c= new Room__c().Id, 
									   ScheduledTime__c=(Time.newInstance(8, 0, 0, 0)), 
									   Status__c= 'In Progress', 
									   Topic__c= topic2.Id);
        Class__c class3 = new Class__c(Name = 'MMM000', 
									   Capacity__c= 10, 
									   DaysPerWeek__c= 3, 
									   Department__c= d1.Id, 
									   StartDate__c=(Date.newInstance(2019, 8, 12)), 
									   EndDate__c=(Date.newInstance(2019, 12, 15)), 
									   Room__c = new Room__c().Id, 
									   ScheduledTime__c=(Time.newInstance(9, 0, 0, 0)), 
									   Status__c= 'In Progress', 
									   Topic__c= topic1.Id);

		Class__c class4 = new Class__c(Name = 'PPP000', 
									   Capacity__c= 10, 
									   DaysPerWeek__c= 5, 
									   Department__c= d2.Id, 
									   StartDate__c=(Date.newInstance(2019, 7, 12)), 
									   EndDate__c=(Date.newInstance(2019, 11, 13)), 
									   Room__c= new Room__c().Id, 
									   ScheduledTime__c=(Time.newInstance(8, 0, 0, 0)), 
									   Status__c= 'In Progress', 
									   Topic__c= topic2.Id);

    
		classes.add(class1);
		classes.add(class2);
        classes.add(class3);
        classes.add(class4);

		insert classes;
		System.debug('Classes Created');

    }
}