force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/duplicateEnrollmentTriggerHelper.cls
public with sharing class duplicateEnrollmentTriggerHelper 
{
    public static final String DUPLICATE_ENROLLMENT = 'That student is already enrolled in the class.';

    // checks a list of enrollments against the existing enrollments to make sure none have the same student in the same class    
    public static void preventDuplicateEnrollment(List<ClassEnrollment__c> enrollmentsBeingInserted)
    {
        // query the database for all class enrollments
        List<ClassEnrollment__c> enrollments = [SELECT Student__c, Class__c FROM ClassEnrollment__c];

        List<ClassEnrollment__c> duplicateEnrollments = new List<ClassEnrollment__c>();

        // loop through every enrollment that already exists and compare them to all the new enrollments
        // a duplicate enrollment is when both the new and existing enrollment have the class and student fields set to the same value
        for(ClassEnrollment__C existingEnrollment: enrollments)
        {
            for(ClassEnrollment__C newEnrollment: enrollmentsBeingInserted)
            {
                if(existingEnrollment.Student__c == newEnrollment.Student__c && existingEnrollment.Class__c == newEnrollment.Class__c)
                {
                    // duplicate enrollments are all added to a single list
                    duplicateEnrollments.add(newEnrollment);
                }
            }
        }
        // adds the error messages and exception for the list of duplicate enrollments
        duplicateEnrollmentErrors(duplicateEnrollments);
    }


    // adds error messages and exception for all duplicate enrollments
    private static void duplicateEnrollmentErrors(List<ClassEnrollment__c> duplicateEnrollments)
    {
        for(ClassEnrollment__c enrollment: duplicateEnrollments)
        {
            enrollment.addError(DUPLICATE_ENROLLMENT);
            throw new DuplicateEnrollmentException(DUPLICATE_ENROLLMENT);
        }
        
    }
}