force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteAttendanceLineHelper.cls
public with sharing class DeleteAttendanceLineHelper {
   public static void deleteAttendanceLineItem (ClassEnrollment__c classEnrollmentBeingDeleted) {
       AttendanceLineItem__c[] attendanceLineItemToBeDeleted = [SELECT Name, ClassEnrollment__c FROM AttendanceLineItem__c WHERE ClassEnrollment__c = :classEnrollmentBeingDeleted.Id];
       try{
           delete attendanceLineItemToBeDeleted;
       }catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
       }
    }

    public static void deleteAttendanceLineItems (List<ClassEnrollment__c> classEnrollmentBeingDeleted) {
        for (ClassEnrollment__c ce : classEnrollmentBeingDeleted) {
            deleteAttendanceLineItem(ce);
        }
    }
}