force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advisor</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClassEnrollmentTest.cls
@isTest
public with sharing class ClassEnrollmentTest {
    @TestSetup
    static void makeData(){
        DepartmentCreator.createDepartment();
        RoomCreator.createRoom();
        TopicCreator.createTopic();
        ClassCreator.createClass();
        AssessmentCreator.createAssessment();
        AdvisorCreator.createAdvisor();
        StudentCreator.createStudent();
        ClassEnrollmentCreator.createClassEnrollment();
        GradeCreator.createGrades();
    }

    @isTest public static void checkDuplicateEnrollment(){
        ClassEnrollment__c newEnrollment = new ClassEnrollment__c();
        Class__c existingClass = [SELECT Id FROM Class__c LIMIT 1];
        Student__c existingStudent = [SELECT Id FROM Student__c LIMIT 1];
        newEnrollment.Class__c = existingClass.Id;
        newEnrollment.Student__c = existingStudent.Id;
        newEnrollment.Credits__c = 3.0;
        Database.SaveResult saveResult= Database.insert(newEnrollment, false);
        System.Assert(saveResult.getErrors()[0].getMessage().contains('Student is already enrolled in the class'));
    }
    @isTest public static void checkAttendanceLineMethods() {
        Student__c newStudent = new Student__c();
        List<Employee__c> testAdvisor = [SELECT Id FROM Employee__c LIMIT 1];
        newStudent.Advisor__c = testAdvisor[0].Id;
        newStudent.Name = 'Jerry Rivera';
        newStudent.Email__c = 'JRivera@gmail.com';
        insert newStudent;

        ClassEnrollment__c newEnrollment = new ClassEnrollment__c();
        Class__c existingClass = [SELECT Id FROM Class__c LIMIT 1];
        newEnrollment.Class__c = existingClass.Id;
        newEnrollment.Student__c = newStudent.Id;
        newEnrollment.Credits__c = 3.0;
        insert newEnrollment;
        
        List<AttendanceLineItem__c> attendanceLineList = [SELECT Id FROM AttendanceLineItem__c WHERE ClassEnrollment__c=:newEnrollment.Id];
        System.assertEquals(1, attendanceLineList.size(), 'The attendance line list is not populating correctly.');

        delete newEnrollment;
        List<AttendanceLineItem__c> lineListAfterDelete = [SELECT Id FROM AttendanceLineItem__c WHERE ClassEnrollment__c=:newEnrollment.Id];
        System.assertEquals(0, lineListAfterDelete.size(), 'The attendance line list is not deleting correctly.');
    }
}