force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Excused__c.field-meta.xml
<CustomField>
    <fullName>Excused__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Excused</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UnExcusedAbsensesTriggerHelper.cls
public with sharing class UnExcusedAbsensesTriggerHelper {

	// a mapping of student id and
	// whether a student can enroll to more classes or not
	public static Map<Id, String> canEnroll = new Map<Id, String>();

	public static void canStudentsEnrollToClasses(Set<Id> studIds) {
		// class enrollments of the students with their corresponding
		// attendance line item
		List<ClassEnrollment__c> enrollments =
		   [SELECT
		   Student__c, Class__c, (SELECT
		   Excused__c, Present__c
		   FROM
		   AttendanceLineItems__r)FROM
		   ClassEnrollment__c 
           WHERE Student__c IN: studIds
		];
        // if student doesn't have any enrollments put 'can_enroll' in the map
        boolean match = false;
        for(Id thisId : studIds){
            match = false;
            for (ClassEnrollment__c cenr : enrollments){
                if(cenr.Student__c.equals(thisId)){
                    match = true;
                    break;
                }
            }
            if(match == false){
                canEnroll.put(thisId, 'can_enroll');
            }
        }
		// a map containing student id and corresponding list of enrollments
		Map<Id, List<ClassEnrollment__c>> studentEnrollments = new
		Map<Id, List<ClassEnrollment__c>>();

		for (ClassEnrollment__c cenr :enrollments) {
			if(studentEnrollments.containsKey(cenr.Student__c)) {
				studentEnrollments.get(cenr.Student__c).add(cenr);
			} else {
				studentEnrollments.put(cenr.Student__c, new List<ClassEnrollment__c>{cenr});
			}
		}
		for(Id thisId :studentEnrollments.keySet()) {
			canEnroll.put(thisId, 
					      canStudentEnrollToClasses(studentEnrollments.get(thisId)));
		}
	}

	public static String canStudentEnrollToClasses(List<ClassEnrollment__c> enrollments) {
		Integer absentCount = 0;
		for(ClassEnrollment__c cenr : enrollments) {
			if(cenr.AttendanceLineItems__r.size() > 0) {
				for (AttendanceLineItem__c att :cenr.AttendanceLineItems__r) {
					if(!(att.Present__c || att.Excused__c)) {
						// if one absense is found, break out of loop
						// because we are concerned about distinct class
						// absenses
						absentCount += 1;
						break;
					}
				}
			}
		}      
		// if student is absent from four or more different classes
		if(absentCount >= 4) {
			return 'expelled';
		} 
        // if student is absent from 3 classes
		else if(absentCount >= 3) {
			return 'cannot_enroll';
		} else {
			return 'can_enroll';
		}

	}
}