force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/DaysPerWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysPerWeek__c</fullName>
    <label>Days per Week</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClassEnrollmentHelper.cls
public with sharing class ClassEnrollmentHelper {
   
   public static void createAttendanceLine(ClassEnrollment__c theEnrollment) {
		Class__c theClass = [
            SELECT
                DaysPerWeek__c
			FROM
            
				Class__c
			WHERE
				Id = :theEnrollment.Class__c
		].get(0);
		// create attendance line item for each day a class meets
		List<AttendanceLineItem__c> attLineItems = new List<AttendanceLineItem__c>();
		for (Integer i = 0; i < theClass.DaysPerWeek__c; i ++) {
			attLineItems.add(new AttendanceLineItem__c(Class__c = theEnrollment.Class__c, 
						     ClassEnrollment__c = theEnrollment.Id, 
						     Student__c = theEnrollment.Student__c));
		}
		try {
			// no partial insertion
			insert attLineItems;
		} catch(DmlException de) {
			System.debug(String.format(UserPermissionErrors.ATT_ERROR, new List<Object>{'create', de.getMessage()}));
		}
	}
	public static void createAttendanceLines(List<ClassEnrollment__c> theEnrollment) {
		for (ClassEnrollment__c c :theEnrollment) {
			createAttendanceLine(c);
		}
	}

	public static void deleteAttendanceLinesForEnrollment(ClassEnrollment__c theEnrollment) {
		AttendanceLineItem__c[] attLineItems = [
            SELECT 
                ClassEnrollment__c
			FROM 
                AttendanceLineItem__c
			WHERE 
				ClassEnrollment__c = :theEnrollment.Id
		];
		try {
			delete attLineItems;
		} catch(DmlException de) {
			System.debug(String.format(UserPermissionErrors.ATT_ERROR, new List<Object>{'delete', de.getMessage()}));
		}
	}
	// used by a trigger
	public static void deleteAttendanceLinesForEnrollments(List<ClassEnrollment__c> theEnrollments) {
		for (ClassEnrollment__c ce :theEnrollments) {
			deleteAttendanceLinesForEnrollment(ce);
		}
	}



}