force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Absent__c.field-meta.xml
<CustomField>
    <fullName>Absent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Absent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Excused__c.field-meta.xml
<CustomField>
    <fullName>Excused__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Excused</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AttendanceLineTriggerHelper.cls
public with sharing class AttendanceLineTriggerHelper {
    public static AggregateResult[] countAbsences(List<AttendanceLineItem__c> enteringALI) {
        List<Id> studentList = new List<Id>();
        List<Student__c> suspendList = new List<Student__c>();
        for (AttendanceLineItem__c line : enteringALI) {
            studentList.add(line.Student__c);
        }
        System.debug('student list: ' + studentList);
        AggregateResult[] absenteeList = [
            SELECT COUNT(Id)absences, Student__c
            FROM AttendanceLineItem__c 
            WHERE (Student__c IN :studentList) 
            AND (Absent__c = true) AND (Excused__c = false)
            GROUP BY Student__c
        ];
        System.debug('absentees: ' + absenteeList.size());
        return absenteeList;
    }
    public static void suspendStudent(AggregateResult[] studentList) {
        List<Id > newList = new List<Id>();
        for (AggregateResult ar : studentList) {
            ar.get('Student__c');
            ar.get('absences');
        }
        List<Student__c> suspendList = [
            SELECT Id, Status__c
            FROM Student__c
            WHERE Id IN :studentList
        ];
        for (Student__c s : suspendList) {
            s.Status__c = suspend;
        }
        try {update suspendList;} catch (DmlException e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
}