force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/DaysPerWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysPerWeek__c</fullName>
    <label>Days per Week</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/DurationInWeeks__c.field-meta.xml
<CustomField>
    <fullName>DurationInWeeks__c</fullName>
    <formula>FLOOR((EndDate__c - StartDate__c) / 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration in Weeks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendanceLineTests.cls
@isTest
public with sharing class AttendanceLineTests {
    @TestSetup
    static void makeData(){
        DepartmentCreator.createDepartment();
        EmployeeCreator.createEmployee();
        StudentCreator.createStudent();

        RoomCreator.createRoom();
        TopicCreator.createTopic();
        ClassCreator.createClass();
    }

    @isTest static void testCreateAttendanceLine() {
        Class__c mockExistingClass = [SELECT Id, DurationInWeeks__c, DaysPerWeek__c FROM Class__c LIMIT 1];
        Student__c mockExistingStudent = [SELECT Id FROM Student__c LIMIT 1];
        ClassEnrollment__c mockNewClassEnrollment = new ClassEnrollment__c();
        mockNewClassEnrollment.Class__c = mockExistingClass.Id;
        mockNewClassEnrollment.Student__c = mockExistingStudent.Id;
        mockNewClassEnrollment.Credits__c = 50;

        Integer mockAttendanceLineNumber = mockExistingClass.DurationInWeeks__c.intValue() * mockExistingClass.DaysPerWeek__c.intValue();

        Test.startTest();
        Database.SaveResult insertResult = Database.insert(mockNewClassEnrollment, false);
        Test.stopTest();

        List<AttendanceLineItem__c> attendanceLineItems = [SELECT Id, Student__c, Class__c FROM AttendanceLineItem__c];

        System.assertEquals(mockAttendanceLineNumber, attendanceLineItems.size());
    }

    @isTest static void testStudentWithdrawFromClass() {
        Class__c mockExistingClass = [SELECT Id FROM Class__c LIMIT 1];
        Student__c mockExistingStudent = [SELECT Id FROM Student__c LIMIT 1];
        ClassEnrollment__c mockNewClassEnrollment = new ClassEnrollment__c();
        mockNewClassEnrollment.Class__c = mockExistingClass.Id;
        mockNewClassEnrollment.Student__c = mockExistingStudent.Id;
        mockNewClassEnrollment.Credits__c = 50;

        Test.startTest();
        Database.insert(mockNewClassEnrollment, false);
        Database.DeleteResult deleteResult = Database.delete(mockNewClassEnrollment, false);
        Test.stopTest();

        List<AttendanceLineItem__c> attendanceLineItems = [SELECT Id, Student__c, Class__c FROM AttendanceLineItem__c];

        System.assertEquals(0, attendanceLineItems.size());
    }
}