force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentWithdrawAttendanceTriggerHelper.cls
public with sharing class StudentWithdrawAttendanceTriggerHelper {
    public static void deleteAttendanceItems (ClassEnrollment__c classEnrollmentBeingDeleted) {
        if (Schema.sObjectType.AttendanceLineItem__c.isAccessible()) {
            delete [SELECT Id FROM AttendanceLineItem__c WHERE ClassEnrollment__c =: classEnrollmentBeingDeleted.Id];
        } else {
            classEnrollmentBeingDeleted.addError(UserPermissionErrors.CANNOT_DELETE_ATTENDANCE_LINE_ITEMS);
        }
    }
}