force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/Absent__c.field-meta.xml
<CustomField>
    <fullName>Absent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Absent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AttendanceLineItem__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AttendanceLineTriggerHelperTests.cls
@isTest
public with sharing class AttendanceLineTriggerHelperTests {
    @TestSetup
    static void makeData() {
        SchoolDataCreator.createData();
    }

    @isTest static void testCountAbsences() {
        // check student status, assert
        List<Student__c> studentList = [
            SELECT Id
            FROM Student__c
            WHERE Status__c = 'Suspended'
        ];
        System.assert(studentList.size() == 0, 'Not yet suspended');

        // grab some attendance line items of student
        studentList = [
            SELECT Id, Status__c, (
                SELECT Id, Absent__c, Student__c
                FROM AttendanceLineItems__r
                LIMIT 3
            )
            FROM Student__c
            LIMIT 3
        ];

        // set absent to true, excused to false (default)
        List<AttendanceLineItem__c> attendanceList = new List<AttendanceLineItem__c>();
        for (Student__c s : studentList) {
            for (AttendanceLineItem__c a : s.AttendanceLineItems__r) {
                a.Absent__c = true;
                attendanceList.add(a);
            }
        }

        // update list of attendance line items
        try {update attendanceList;} catch (DmlException e) {
            System.debug('Error: ' + e.getMessage());
        }    

        // check student status, assert
        studentList = [
            SELECT Id
            FROM Student__c
            WHERE Status__c = 'Suspended'
        ];
        System.assert(studentList.size() == 3, 'Now suspended');
    }
}