force-app/main/default/objects/AttendanceLineItem__c/AttendanceLineItem__c.object-meta.xml
<CustomObject>
    <label>Attendance Line Item</label>
    <nameField>
        <displayFormat>ALI-{0000}</displayFormat>
        <label>Attendance Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttendanceLineItem__c/fields/ClassEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ClassEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Attendance Line Items</relationshipLabel>
    <relationshipName>AttendanceLineItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendanceLineTriggerTest.cls
@isTest
public with sharing class AttendanceLineTriggerTest {
    @TestSetup
    static void makeData()
    {
        SchoolDataCreator.createData();

    }  
     @isTest static void testAttendanceLineInsert() {
        List<AttendanceLineItem__c> beforeCE = [SELECT Id FROM AttendanceLineItem__c];
		ClassEnrollmentCreator.createClassEnrollment();
        List<AttendanceLineItem__c> afterCE = [SELECT Id FROM AttendanceLineItem__c];
        System.assertEquals(24, afterCE.size() - beforeCE.size());
     }

    @isTest static void testAttendanceLineDelete() {
        ClassEnrollmentCreator.createClassEnrollment();
		ClassEnrollment__c ce = [SELECT Id FROM ClassEnrollment__c LIMIT 1];
        delete ce; 
        List<AttendanceLineItem__c> a1 = [SELECT Id FROM AttendanceLineItem__c WHERE AttendanceLineItem__c.ClassEnrollment__r.Id=:ce.Id];
        System.assert(a1.isempty());
     }
}