force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Credits__c.field-meta.xml
<CustomField>
    <fullName>Credits__c</fullName>
    <label>Credits</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Expelled</fullName>
            </value>
            <value>
                <fullName>Graduated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Project1Tests.cls
@isTest//(seeAllData=true)
public with sharing class Project1Tests {
    @TestSetup
    static void makeData(){
        Account acc = new Account(
            Name = 'test', 
            BillingState = 'CA');
        insert acc;
        Contact cc = new Contact(
            LastName = 'test', 
            MailingState = 'CA',
            AccountId = acc.id);
        insert cc;
        Account acc2 = new Account(Name = 'test');
        insert acc2;
        
        SchoolDataCreator.createData();
        // Class Enrollment creator
        ClassEnrollment__c ce = new ClassEnrollment__c(
            Class__c = [SELECT Id FROM Class__c][0].Id, 
            Student__c = [SELECT Id FROM Student__c][0].Id, 
            Credits__c = 1, 
            Status__c = 'Enrolled'
            ); insert ce;
        // Grade creator
        for (Integer i = 0; i < 3; i++) {
            Grade__c g = new Grade__c(
                Assessment__c = [SELECT Id FROM Assessment__c][0].Id,
                Class_Enrollment__c = [SELECT Id FROM ClassEnrollment__c][0].Id,
                Grade__c = 70 + 10 * i
            ); insert g;
        }
    }
    @isTest static void testFibonacci() {
        Integer zeroth = Project1.fibonacci(0);
        Integer first = Project1.fibonacci(1);
        Integer eighth = Project1.fibonacci(46); 
        Integer negative = Project1.fibonacci(-1);

        System.assertEquals(0, zeroth);
        System.assertEquals(1, first);
        System.assertEquals(1836311903, eighth);
        System.assertEquals(-1, negative);
    }
    @isTest static void testReverseString() {
        String even = Project1.reverseString('Hello world!');
        String odd = Project1.reverseString('Racecar');
        String empty = Project1.reverseString('');

        System.assertEquals('Hello world!'.reverse(), even);
        System.assertEquals('Racecar'.reverse(), odd);
        System.assertEquals(''.reverse(), empty);
    }
    @isTest static void testFactorial() {
        Integer zeroth = Project1.factorial(0);
        Integer first = Project1.factorial(1);
        Integer fifth = Project1.factorial(5);
        Integer negative = Project1.factorial(-4);

        System.assertEquals(1, zeroth);
        System.assertEquals(1, first);
        System.assertEquals(120, fifth);
        System.assertEquals(-1, negative);
    }
    @isTest static void testPalindrome() {
        String even = Project1.reverseString('anna');
        String odd = Project1.reverseString('racecar');
        String empty = Project1.reverseString('');

        System.assertEquals('anna', even);
        System.assertEquals('racecar', odd);
        System.assertEquals('', empty);
    }
    @isTest static void testStateAccounts() {
        List<Account> all = [SELECT Id, Name FROM Account];
        List<Account> accounts = Project1.getAccountsForAGivenState(State.CA);

        System.assertEquals(2, all.size(), 'all accounts');
        System.assertEquals(1, accounts.size(), 'CA accounts');
    }
    @isTest static void testStudentClassGrades() {
        Map<Id, Map<Id, Double>> classGrades = Project1.getClassGrades();
        for (Map<Id, Double> m : classGrades.values()) {
            for (Double d : m.values()) {
                System.assertEquals(true, d < 100 && d > 50, 'Average');
            }
        }
    }
}