force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GradeCreator.cls
public with sharing class GradeCreator {
    
    public static void createGrades() {
        List<ClassEnrollment__c> mockEnrollment= [SELECT Id FROM ClassEnrollment__c LIMIT 1];
        List<Assessment__c> mockAssessment = [SELECT Id FROM Assessment__c LIMIT 1];
        System.debug('Mock assessment: ' + mockAssessment);
        List<Grade__c> gradeList = new List<Grade__c>();
        Grade__c testGrade = new Grade__c();
        testGrade.Class_Enrollment__c = mockEnrollment[0].Id;
        testGrade.Assessment__c = mockAssessment[0].Id;
        testGrade.Grade__c = 80.0;
        gradeList.add(testGrade);

        Grade__c testGradeTwo = new Grade__c();
        testGradeTwo = new Grade__c();
        testGradeTwo.Assessment__c = mockAssessment[0].Id;
        testGradeTwo.Class_Enrollment__c = mockEnrollment[0].Id;
        testGradeTwo.Grade__c = 90.0;
        gradeList.add(testGradeTwo);
        insert gradeList;
    }
}