force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>What date is this Assessment on/due?</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <inlineHelpText>What time is this assessment due?</inlineHelpText>
    <label>Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/DaysPerWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysPerWeek__c</fullName>
    <label>Days per Week</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>Rm-{0000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssessmentTriggerTests.cls
@isTest()
public with sharing class AssessmentTriggerTests {
    @TestSetup
    static void setup(){
        DepartmentCreator.createDepartment();
        RoomCreator.createRoom();
        TopicCreator.createTopic();
        ClassCreator.createClass();
        AssessmentCreator.createAssessment();
    }

    /**
        Assessment being created and an Assessment using the room
     */
    @isTest static void testDoubleBookingAssessmentWithExistingAssessment() {
        Class__c mockExistingClass = [SELECT Id FROM Class__c LIMIT 1];
        Assessment__c mockNewAssessment = new Assessment__c();
        mockNewAssessment.Name = 'MockAssessment';
        mockNewAssessment.Class__c = mockExistingClass.Id;
        mockNewAssessment.Date__c = Date.newInstance(2075,9,16);
        mockNewAssessment.Time__c = Time.newInstance(9,0,0,0);

        checkDoubleBooking(mockNewAssessment);
    }

    /**
        Assessment being created and an Assessment using the room
     */
    @isTest static void testDoubleBookingAssessmentWithExistingClass() {
        Class__c mockExistingClass = [SELECT Id FROM Class__c LIMIT 1];
        Assessment__c mockNewAssessment = new Assessment__c();
        mockNewAssessment.Name = 'MockAssessment';
        mockNewAssessment.Class__c = mockExistingClass.Id;
        mockNewAssessment.Date__c = Date.newInstance(2050,1,4);
        mockNewAssessment.Time__c = Time.newInstance(9,0,0,0);

        checkDoubleBooking(mockNewAssessment);
    }

    // @isTest static void testDoubleBookingClass() {
    //     Class__c newClass = new Class__c();

    //     Department__c existingDepartment = [SELECT Id FROM Department__c LIMIT 1];
    //     newClass.Department__c = existingDepartment.Id;
    //     newClass.daysPerWeek__c = 1;
    //     newClass.StartDate__c = Date.newInstance(2050,1,1);
    //     newClass.EndDate__c = Date.newInstance(2050,1, 10);
    //     newClass.ScheduledTime__c = Time.newInstance(9,0,0,0);

    //     Room__c existingRoom = [SELECT Id FROM Room__c LIMIT 1];
    //     newClass.Room__c = existingRoom.Id;
    //     Topic__c existingTopic = [SELECT Id FROM Topic__c LIMIT 1];
    //     newClass.Topic__c = existingTopic.Id;

    //     checkDoubleBooking(newClass);
    // }

    static void checkDoubleBooking(sObject classOrAssessment) {
        Test.startTest();
        Database.SaveResult insertResult = Database.insert(classOrAssessment, false);
        Test.stopTest();

        // Insertion should have been stopped by the user.
        System.assert(!insertResult.isSuccess());
        // If it's stopped correctly, we should also receive an error
        System.assert(insertResult.getErrors().size() > 0);
        // This error should say `This room will be occupied during that time. Please choose another.`
        System.assertEquals('This room will be occupied during that time. Please choose another.',
                             insertResult.getErrors()[0].getMessage());
    }
}