force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>Class_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Grade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grade__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Class_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Class_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class Enrollment</label>
    <referenceTo>ClassEnrollment__c</referenceTo>
    <relationshipLabel>Grades</relationshipLabel>
    <relationshipName>Grades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grade__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/P0.cls
public with sharing class P0 {
    
    // Return the nth fiboacci number in the fibonacci sequence.
    public static integer Fibonacci(integer n) { 
        integer num1 = 1;
        integer num2 = 1;
        for (integer i=2; i<n; i++) {
            integer fibo = num2 + num1;
            num1 = num2;
            num2 = fibo;
        }
        return num2;
    }

    //Given a string, return its backwards order.
    public static String reverseString(String s) {
        integer stringLength = s.length();
        String[] arrayOfString = new List<String>();
        for(integer i=stringLength-1; i>=0; i--) {
            arrayOfString.add(s.substring(i,i+1));
        }
        s = String.join(arrayOfString,'');
        return s;
    }

    //Given a string, determine if it is a palindrome
    public static Boolean isPalindrome(String s) {
        if(P0.reverseString(s)==s)
        return true;
        else {
            return false;
        }
    }

    //computes the factorial of a given number using recursion.
    public static Integer factorial(Integer n) {
        if(n>=1){
            return n*factorial(n-1);
        }
        else {
            return 1;
        }
    }

    //Given a state, return the accounts in that state
    public static List<Account> getAccountsForAGivenState(State s) {
       Account[] acc = [SELECT Account.Name, ( SELECT FirstName, LastName FROM Contacts WHERE MailingState=:s.name() ) FROM Account WHERE BillingState=:s.name()];
        return acc;
    }


    //For each student, get the grade for each of their classes
    public static Map<Id, Map<Id, Double>> getClassGrades() {
        
        List<ClassEnrollment__c> classenrollments = [SELECT Name, Id,ClassEnrollment__c.Class__r.Id, ClassEnrollment__c.Student__r.Name, ClassEnrollment__c.Student__r.Id FROM ClassEnrollment__c];// 
        List<Grade__c> grades = [SELECT Name, Grade__c, Grade__c.Class_Enrollment__r.Student__c, Grade__c.Class_Enrollment__r.Name,Grade__c.Class_Enrollment__r.Id, Grade__c.Assessment__r.Name FROM Grade__c];
        List<Student__c> students = [SELECT Id FROM Student__c];
        Map<Id, Map<Id, Double>> avgGradeForStudent = new Map<Id, Map<Id, Double>>();
        for(Student__c stud : students){ // For each student
             Map<Id, Double> averageGradeForClass = new Map<Id, Double>();
        	for (ClassEnrollment__c ce : classenrollments) { // For each class enrollment
            	Double sumOfGrade = 0.0;
            	Double numberOfGrades = 0.0;
            	Double avgGrade = 0.0;
                if(ce.Student__c == stud.Id){
            	for (Grade__c gr : grades) {
                	if((ce.Id == gr.Class_Enrollment__c)){
                    	sumOfGrade += gr.Grade__c;
                    	numberOfGrades += 1;
                    	avgGrade = sumOfGrade/numberOfGrades; //Average Grade
                    } 
                averageGradeForClass.put(ce.Id,avgGrade);// Average grade for each class enrollments   
                }
                avgGradeForStudent.put(ce.Student__c, averageGradeForClass); 
                }
            } 

        }
        return avgGradeForStudent; 
    }
}