force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>What date is this Assessment on/due?</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <inlineHelpText>What time is this assessment due?</inlineHelpText>
    <label>Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClassTriggerHelper.cls
public with sharing class ClassTriggerHelper {
    // /**
    //     Given an Assessment, check if there is a Class or Assessment using that room at the specified time.
    //  */
    // public static void preventDoubleRoomBooking(Class__c assessmentBeingInserted) {
    //     // Get existing assessment
    //     List<Assessment__c> existingAssessments;
         
    //     if (Schema.sObjectType.Assessment__c.isAccessible()) {
    //         existingAssessments = [SELECT Id FROM Assessment__c WHERE Date__c =: assessmentBeingInserted.Date__c AND Time__c =: assessmentBeingInserted.Time__c];
    //     }

    //     if (existingAssessments != null && existingAssessments.size() > 0) {
    //         assessmentBeingInserted.addError('This room will be occupied during that time. Please choose another.');
    //     }

    //     checkIfClassIsScheduledDuringAssessment(assessmentBeingInserted);

    // }


    // static void checkIfClassIsScheduledDuringAssessment(Assessment__c assessmentBeingInserted) {
    //     List<Class__c> existingClasses;

    //     if (Schema.sObjectType.Class__c.isAccessible()) {
    //         existingClasses = [SELECT Id FROM Class__c WHERE (StartDate__c <: assessmentBeingInserted.Date__c) AND (EndDate__c >: assessmentBeingInserted.Date__c) AND (ScheduledTime__c =: assessmentBeingInserted.Time__c)];
    //     }
    //     if (existingClasses != null && existingClasses.size() > 0) {
    //         assessmentBeingInserted.addError('This room will be occupied during that time. Please choose another.');
    //     }
    // } 
}