force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RoomUtilityClass.cls
public with sharing class RoomUtilityClass {
    public static void checkIfRoomIsBeingUsed(List<sObject> classesOrAssessmentsAlreadyExisting, sObject assessmentOrClassBeingInserted) {
        if (classesOrAssessmentsAlreadyExisting != null) { // User has at least read access
            if (classesOrAssessmentsAlreadyExisting.size() > 0) { // Double booking
                assessmentOrClassBeingInserted.addError('This room will be occupied during that time. Please choose another.');
            }
        } else { // User cannot read Class  
            if (assessmentOrClassBeingInserted instanceOf Assessment__c) { 
                assessmentOrClassBeingInserted.addError('You do not have access to see Assessment records. Please contact System Administrator for more details.');
            } else if (assessmentOrClassBeingInserted instanceOf Class__c) {
                assessmentOrClassBeingInserted.addError('You do not have access to see Class records. Please contact System Administrator for more details.');
            }
        }
    }

    /**
        Given a list of Assessments or Classes, return an error to view stating that the room has been double booked.
    */
    public static void denyRecordsTryingToDoubleBookRoom(List<sObject> classesOrAssessmentsToBeDenied) {
        for (sObject obj: classesOrAssessmentsToBeDenied) {
            obj.addError('This room will be occupied during that time. Please choose another.');
        }
    }
}