force-app/main/default/objects/ClassEnrollment__c/ClassEnrollment__c.object-meta.xml
<CustomObject>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>CE-{0000}</displayFormat>
        <label>Class Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassEnrollment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>ClassEnrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DuplicateEnrollmentHelper.cls
/**
 * Created by gamedevmadeeasy on 10/17/19.
 */

public class DuplicateEnrollmentHelper {
    public static void DuplicateCheckHelper(List<ClassEnrollment__c> classes){
        try {
            Set <String> classEnrollmentSet = new Set<String>();
            Set <String> studentSet = new Set<String>();

            for (ClassEnrollment__c classEnrollment : classes) {
                classEnrollmentSet.add(classEnrollment.Id);
                studentSet.add(classEnrollment.Student__r.Id);
            }

            List <ClassEnrollment__c> classEnrollments = new List<ClassEnrollment__c>();

            classEnrollments = [SELECT Id FROM ClassEnrollment__c WHERE Id IN :classEnrollmentSet OR Student__c IN :studentSet];

            for (ClassEnrollment__c ce : classes) {
                If (classEnrollments.size() > 0) {
                    // Displaying the error
                    ce.addError( 'Duplicate Student Found in this Class Enrollment.' );
                }
            }
        }
        catch (DuplicateEnrollmentException duplicateEnrollmentException) {
            duplicateEnrollmentException.getMessage();
        }
    }
}